### PR TITLE
feat: add rss support [SPMVP-4660]

### PR DESCRIPTION
**Pull request by ches4117**
## Jira

[//]: # 'This template is for new features, or changing an existing feature'
[//]: # 'Put the related jira links here'
[//]: # 'Please ensure there has description for the feature'

https://storipress-media.atlassian.net/jira/software/projects/SPMVP/boards/1?selectedIssue=SPMVP-4660

## Purpose

[//]: # 'Please describe how the feature will affect user, e.g.'
[//]: # '- Allow to add link on image so publisher can directly link an image in static site'
[//]: # '- Adjust "Go to site" button to become "Go to Shopify" to let publisher using Shopify integration can directly go to see preview'
[//]: # (User should be one of "reader" {who read publisher's articles}, "publisher" {our users}, "developer" {us})

Add rss support

### For who

- [ ] reader-facing?
- [x] publisher-facing?
- [ ] developer-facing?

## How did you make it?

[//]: # 'Give a brief for the changes you made'

use [feed](https://github.com/jpmonette/feed) to generate atom file 

## Production deployment notes

[//]: # 'Please describe the production deployment notes, e.g. this changes depend on other API or module change'

## 🎩 Tophat

Do a thorough 🎩. What is [tophatting](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md_)?

Consider testing:

- Existing functionality which could break due to your changes (e.g. global changes)
- New functionality being introduced. Ensure it meets intended behavior
- All different permutations (flows, states, conditions, etc) that are possible
- If you are modifying something which is used in multiple places, 🎩 all affected areas not just what you intend to change

### 🎩 Instructions

[//]: # "If it's complex, consider put a screen record here"

1. yarn karbon in karbon
2. yarn dev in playground
3. go to http://localhost:3000/atom.xml
4. show the page success ⭕ 

## Related PRs

[//]: # 'Put the related PRs here, e.g. PR in core-component'

## Checklist before requesting review

- [x] I have done a self-review of my own code (comment on code is not required but recommended)
- [x] I did the Tophat steps and confirm the feature is working
- [x] I have confirmed there is no issue reported by Static Analyzer (Please double check for custom class. For other issues, if you think it's ignorable, please add `// eslint-ignore-next-line <rule name>` on it)
- [ ] I have confirmed there is no deepsource issue (if you think it's ignorable, please explain why and add a [`skipcq` comment](https://deepsource.io/blog/releases-silence-issues-in-code/))
- [ ] I confirmed that the unit test is passed (if you break it, please fix it in this PR)
- [ ] I confirmed that I didn't break E2E test (if you break it, please fix it or create a new Jira)

## Emoji Guide

**For reviewers: Emojis can be added to comments to call out blocking versus non-blocking feedback.**

E.g: Praise, minor suggestions, or clarifying questions that don’t block merging the PR.

> 🟢 Nice refactor!

> 🟡 Why was the default value removed?

E.g: Blocking feedback must be addressed before merging.

> 🔴 This change will break something important

|              |                |                                     |
| ------------ | -------------- | ----------------------------------- |
| Blocking     | 🔴 ❌ 🚨       | RED                                 |
| Non-blocking | 🟡 💡 🤔 💭    | Yellow, thinking, etc               |
| Praise       | 🟢 💚 😍 👍 🙌 | Green, hearts, positive emojis, etc |

## Gif (optional)

image

### CODE REVIEW

**Review by DanSnow — CHANGES_REQUESTED** [review]
是不是忘記推 package.json 之類的上來了，有 `feed` 套件找不到的問題

**Comment by ches4117** [comment]
> 是不是忘記推 package.json 之類的上來了，有 `feed` 套件找不到的問題

是, 忘記推上, 抱歉, 已補推上

**Review by DanSnow — CHANGES_REQUESTED** [review]
目前產生的 summary 的內容看起來像是 slug ，這邊能看看嗎？
image

**Comment by ches4117** [comment]
> 目前產生的 summary 的內容看起來像是 slug ，這邊能看看嗎？ image

好, 我看看

**Review by DanSnow — APPROVED** [review]

**Pull request merged**
